### ISSUE TITLE
Error integracion

### ISSUE THREAD

**Issue by nasdarhome** [jbouwh/ha-elro-connects#15]
Hello thanks for your amazing integration. When adding the integration it shows me this error:

Reintentando la configuración: Not received the expected result, cannot connect to hub 192.168.1.103 with id ST_xxxxxxxxxx. ('Expecting property name enclosed in double quotes: line 1 column 2 (char 1)',)

port: 1025
version: v0.1.10

port: 1025
version: v0.1.10
elro devices, those manufactured by siterwell, my devices have not been bought from elro but from siterwell.

sorry my english is not very good and i'm translating from google

**Comment by nasdarhome** [comment]
Sorry, I had a problem with the wifi connection. it's already solved

**Comment by jbouwh** [comment]
I see that your setup is in Spanish. Currently only Dutch and English have a translation. I hope to solve that in the future.  Nice you solved your issue. Feel free to report any issues.

**Comment by jbouwh** [comment]
Added Spanish and Portuguese as languages

**Comment by nasdarhome** [comment]
Muchas gracias por el excelente trabajo. Gracias a tu integración más dispositivos como los de siterwell son compatibles.
Buen trabajo

Thank you very much for the excellent work. Thanks to your integration, more devices such as siterwell are compatible.

Good job

Enviado desde mi iPhone

El 5 sept 2022, a las 20:35, Jan Bouwhuis ***@***.***> escribió:

﻿

Added Spanish and Portuguese as languages

**Comment by jbouwh** [comment]
Nice to hear that!
