### ISSUE TITLE
k2

### ISSUE THREAD

**Issue by Tom-Bon92** [jbouwh/ha-elro-connects#18]
Hi, I know thit is not a issue.
But i don't get it worked with a k2.

If you wan't to try something with a k2, i've got one and if you want  I can make a test.

**Comment by jbouwh** [comment]
I expect the K2 connector has a completely different architecture compared to the K2. I have no documentation nor a K2 connector to test with. If anything comes to my path that can be worked out, then I'll give it a try.

**Comment by alexkoel1958** [comment]
The problem is that the K1 Connect is not sold anymore. If you are living in the neigborhood of Ter Aar, I can loan you my K2 to build a integration. :-)

**Comment by jbouwh** [comment]
I know, the K2 connector though works completely different. Unfortunately there is no help from the manufacturer to supply documentation or whatsoever. So there is not much I can do. May be there is someone that will do a contribution later, when there is more information available.
