### ISSUE TITLE
Had a real fire alarm, but no status update in HA

### ISSUE THREAD

**Issue by erwin-willems** [jbouwh/ha-elro-connects#33]
Had a fire alarm last night at 4:30 am. Luckily it was a false alarm. I checked the Elro app and found one detector which reported a fire alarm. 
But this alarm was not reported in Home Assistant. All detectors still report "Device_state NORMAL". None of them have changed, nor in the history log.

I haven't checked this issue yet in detail, will do that this weekend. But I wanted to report this already. This weekend I will run several test runs. As far as I know, that should change the Device_state as well. Is that true?

I will add details of my findings later. So no action is required yet on this issue.

**Comment by jbouwh** [comment]
It is possible the k1 connector was not polled while the status was changed. The Elro app is triggered via the API, that is a different route. I did test once to see how the status changes on the connector, and that worked. So no idea why there was no detection in your case.

**Comment by erwin-willems** [comment]
This issue can be closed. Had again a fire alarm (again false alarm), but got triggers this time:

![image](https://user-images.githubusercontent.com/17808387/228492381-787a748d-2cd0-4b72-963f-6e6a83eda837.png)

After my previous alarm a month ago, I did a removal/add of the integration to reload all devices. Looks like that worked
