### ISSUE TITLE
When testing with real smoke I see something strange.

### ISSUE THREAD

**Issue by AlbertDijksma** [jbouwh/ha-elro-connects#5]
Hi Jan,
Thank you for this beautiful elro integration and all the time you have invested in it.
I have a k1 and 6 smoke detectors.
Installed the elro integration via hacs without problems v0.1.5-1
When testing with real smoke I see something strange.
The status goes from NORMAL to n/a and only when the smoke alarm is almost gone it go to the FIRE ALARM status
![elro](https://user-images.githubusercontent.com/25565832/179396628-1bd4ed54-599b-437c-a215-96a2717de0ed.jpg)

**Comment by jbouwh** [comment]
Well that is interresting indeed. I did not do a live smoke test to see its output. The n/a state is some state that is not recognized yet. This is something to be solved in the backend `lib-elro-connects`. May be you can file the error there. There is some test code (example) so you could find out what kind of output there is in case of a real alarm.

**Comment by jbouwh** [comment]
Have been testing today, and caused a fire alarm. But was not able to catch the unknown code yet.

**Comment by jbouwh** [comment]
I will update the library soon so it will return the hexcode instead of `n/a`.

**Comment by AlbertDijksma** [comment]
Hello,
I did a real smoke test with version 0.1.7
First get a status 22 before the status FIRE ALARM comes
![elro2](https://user-images.githubusercontent.com/25565832/182385542-7006b373-fbfa-4558-a4c9-4bddbf689d4f.jpg)
n

**Comment by jbouwh** [comment]
Thnx a lot, tat helps! I will add this state so it will be identified as `FIRE_ALARM`. I do not know what the difference is between the 2 states. An unknown state should not been seen anymore.

**Comment by jbouwh** [comment]
https://github.com/jbouwh/ha-elro-connects/pull/9

**Comment by jbouwh** [comment]
v0.1.8 shoud fix it

**Comment by AlbertDijksma** [comment]
Case may be closed.
Everything works.
Thank you

**Comment by jbouwh** [comment]
> Case may be closed. Everything works. Thank you

Thnx @AlbertDijksma for your help!
